apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: '87.15.1'
    chart: kube-prometheus-stack
    helm: 
      values: |
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - prometheus.mycompany.test
            paths:
              - /
            pathType: Prefix
          prometheusSpec: 
            nodeSelector: 
              workload-type: monitoring
            tolerations:
              - key: "dedicated"
                operator: "Equal"
                value: "monitoring"
                effect: "NoSchedule"
            resources:
              requests:
                memory: 512Mi
                cpu: 100m
              limits: 
                memory: 750Mi
                cpu: 500m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp3-dev-sc
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          nodeSelector:
            workload-type: monitoring
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "monitoring"
              effect: "NoSchedule"
          persistence:
            enabled: true
            storageClassName: gp3-dev-sc
            size: 10Gi
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 300m
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations: 
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:  
              - grafana.mycompany.test
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations: 
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:  
              - alerts.mycompany.test
            paths: 
              - /
            pathType: Prefix
          alertmanagerSpec:
            nodeSelector:
              workload-type: monitoring
            tolerations:
              - key: "dedicated"
                operator: "Equal"
                value: "monitoring"
                effect: "NoSchedule"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp3-dev-sc

                  accessModes:
                    - ReadWriteOnce

                  resources:
                    requests:
                      storage: 5Gi
                        
        prometheusOperator:
          nodeSelector:
            workload-type: monitoring
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "monitoring"
              effect: "NoSchedule"
          resources:  
            requests:
              memory: 150Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 300m
        kube-state-metrics:
          nodeSelector:
            workload-type: monitoring
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "monitoring"
              effect: "NoSchedule"        
        prometheus-node-exporter:
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "monitoring"
              effect: "NoSchedule"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:  
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true