apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://SonarSource.github.io/helm-chart-sonarqube'
    targetRevision: '2026.3.1'
    chart: sonarqube
    helm:
      #FYI memory= 256Mi   # 256MB of RAM
      #FYI cpu= 250m       # 1vCPU/core = 1000m (250m = 0.25 of single core, 25%)
      values: |
        monitoringPasscodeSecretName: sonarqube-monitoring-passcode
        monitoringPasscodeSecretKey: SONAR_WEB_SYSTEMPASSCODE
        nodeSelector:
          node.kubernetes.io/instance-type: c7i-flex.large
          workload-type: monitoring
        jvmOpts: "-Xmx768m -Xms768m"
        elasticsearch: 
          jvmOpts: "-Xmx768m -Xms768m"
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
        initContainers:
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "monitoring"
              effect: "NoSchedule"
        persistence:
          enabled: true
          # A standard gp3 default storage class will be used
          size: 5Gi
          storageClass: gp3-dev-sc
          accessMode: ReadWriteOnce
        postgresql:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 15.10.0-debian-12-r0
          postgresqlUsername: sonarUser
          postgresqlPassword: sonarPass
          postgresqlDatabase: sonarDB

          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 20Gi
            storageClass: gp3-dev-sc

          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m

          nodeSelector:
            workload-type: monitoring

          tolerations:
            - key: dedicated
              operator: Equal
              value: monitoring
              effect: NoSchedule                 
        resources:  
          requests:
            memory: 1.5Gi
            cpu: "500m"
          limits:
            memory: 2800Mi
            cpu: "1"
        ingress: 
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/proxy-body-size: "64m"
          hosts:
            - name: sonarqube.mycompany.test
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true