apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: vault
    targetRevision: 0.28.0
    helm:
      values: |
        server:
          enabled: true
          # this should match with TF SA we created in TF vault module eks identity
          serviceAccount:
            create: true
            name: "vault"
          # Ingress for vault UI 
          ingress:         
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
              - host: vault.mycompany.test
                paths:
                  - /
          # HA for vault
          ha:
            enabled: true
            replicas: 2
            raft:
              enabled: true
              setNodeId: true
            config: |
              ui = true
              listener "tcp"{
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                }
              storage "raft" {
                path = "/vault/data"
                # Crucial Fix: Allows the pods to locate each other and form the cluster
                retry_join {
                  leader_api_addr = "http://vault-0.vault-internal:8200"
                }
                retry_join {
                  leader_api_addr = "http://vault-1.vault-internal:8200"
                }
                retry_join {
                  leader_api_addr = "http://vault-2.vault-internal:8200"
                }
                }
              # Crucial Fix: Required for Kubernetes Raft cluster sync
              service_registration "kubernetes" {}
              
              seal "awskms" {
                region = "us-east-1"
                kms-key-id = "6bd48b85-caf2-400e-961a-f0b1551f3be3"
                }
          nodeSelector:
            karpenter.sh/capacity-type: "on-demand"
            

          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: gp3-dev-sc
            accessMode: ReadWriteOnce 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: hashicorp-vault-agent-injector-cfg
      jqPathExpressions:
        - '.webhooks[].clientConfig.caBundle'