# ---------------------------------------------------------
# 2. NodePool: The "Scaling" Rules
# Tells Karpenter when to launch nodes and what sizes are allowed
# ---------------------------------------------------------
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-aws-karp
spec:
  template:
   # metadata:
    #  labels:
     #   karpenter.sh/initialized: "true"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ec2nodeclass-aws-karp
      
      # The Rules: What kind of servers is Karpenter allowed to buy?
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"] # Standard Intel/AMD processors
          
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.small", "t3.micro"]
          
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"] # Tell Karpenter to use cheap Spot instances first!

  # Maximum total CPUs Karpenter is allowed to spin up across the whole cluster
  limits:
    cpu: 100
    
  # Enterprise Standard: Kill nodes instantly if they are empty for 1 minute
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m