name: Terraform Workflow
on:
    pull_request:
        branches: ["staging","main"]
        types: [opened, synchronize, ready_for_review, reopened]
        paths: 
          - 'envs/development/**'
          - 'modules/**'
    push:
        branches: ["main","staging"]
        paths:
          - 'envs/development/**'
          - 'modules/**'
permissions:            #per for OIDC token generation and PR comments
    id-token: write
    contents: read
    pull-requests: write
env:                    #to setup the tf env before reading .tf files we need to declare this
    AWS_REGION: "us-east-1"
    TF_VERSION: "1.10"
    AWS_ACCOUNT_ID: "059325865650"

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true  #true:old wk will be cancelled false: wait until finish old job

jobs:
    security-check:
        name: "Static analysis & security check"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Configure AWS creds for plan role
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::059325865650:role/terraform-plan-role
                aws-region: ${{ env.AWS_REGION }}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ env.TF_VERSION }}
            - name: Terraform format check
              run: terraform fmt -check -recursive         #check: pipeline fail if any issue in tf file, recursive: depply scans all the dir
            - name: Setup TFlint            #this will do advanced check like security issues, optimization errors or any inproper values like ec2 type t2.microooo, etc
              uses: terraform-linters/setup-tflint@v4
            - name: Run TFlint
              run: tflint -f compact        #tflint will check and give result in compact fmt
            - name: Run security scan
              uses: bridgecrewio/checkov-action@v12
              continue-on-error: true
              with:
                directory: .
                framework: terraform
                soft_fail: false        #fails the job if checkov finds violation
                quiet: true
            #- name: Setup Infracost
            #  uses: infracost/actions/setup@v2
            #  with: 
            #    api-key: secrets.INFRACOSTAPI
            #- name: Generate Infracost Breakdown
            #  run: infracost breakdown --path . --format json --out-file infracost.json
    
    tf-plan:
        name: "Plan for each layer"
        runs-on: ubuntu-latest
        needs: security-check
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure AWS creds for plan role
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::059325865650:role/terraform-plan-role
                aws-region: ${{ env.AWS_REGION }}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ env.TF_VERSION }}
            - name: TF init and plan for networking
              working-directory: envs/development/networking
              #env:
                #TF_LOG: DEBUG
                #not needed bcaz we already using OIDC same role
                #TF_VAR_role_to_assume: arn:aws:iam::156985228858:role/terraform-plan-role
              run: |
                terraform init
                terraform validate
                terraform plan -no-color -out=tfplan > ../../../plan-net.txt
            - name: TF init and plan for iam
              working-directory: envs/development/iam
              run: |
                terraform init
                terraform validate
                terraform plan -no-color -out=tfplan > ../../../plan-iam.txt
            - name: TF init and plan for kube
              working-directory: envs/development/kube
              run: | 
                terraform init
                terraform validate
                terraform plan -no-color -out=tfplan > ../../../plan-kube.txt
            - name: Update PR with plan
              uses: actions/github-script@v7
              if: github.event_name == 'pull_request'
              with:
                github-token: ${{ github.token }}
                script: |
                    const fs = require('fs');       //import node.js filesystem
                    const netPlan = fs.readFileSync('plan-net.txt','utf8')
                    const iamPlan = fs.readFileSync('plan-iam.txt','utf8');
                    const kubePlan = fs.readFileSync('plan-kube.txt','utf8');
                    const output = `#### Terraform plan
                    <details><summary>Layer 1: Networking Show plan</summary>

                    \`\`\`terraform\n
                    ${netPlan}
                    \`\`\`
                    </details>
                    <details><summary>Layer 1: Networking Show plan</summary>

                    \`\`\`terraform\n
                    ${iamPlan}
                    \`\`\`
                    </details>
                    <details><summary>Layer 1: Networking Show plan</summary>

                    \`\`\`terraform\n
                    ${kubePlan}
                    \`\`\`
                    </details>

                    *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: output
                    })
    apply:
        name: "Terraform apply"
        runs-on: ubuntu-latest
        needs: tf-plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure AWS credential
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::059325865650:role/terraform-apply-role
                aws-region: ${{ env.AWS_REGION }}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ env.TF_VERSION }}
            - name: Terraform init and apply for Net
              working-directory: envs/development/networking
              run: |
                terraform init
                terraform apply -auto-approve
            - name: Terraform init and apply for iam
              working-directory: envs/development/iam
              run: |
                terraform init
                terraform apply -auto-approve
            - name: Terraform init and apply for kube
              working-directory: envs/development/kube
              run: |
                terraform init
                terraform apply -auto-approve

